version: '3.4'
services:
  lighthouse-zinken-beacon-chain.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v0.3.0
    image: 'lighthouse-zinken-beacon-chain.dnp.dappnode.eth:0.1.0'
    restart: always
    environment:
      - 'HTTP_WEB3PROVIDER=http://goerli-geth.dappnode:8545'
      - EXTRA_OPTS
    volumes:
      - 'data:/data'
    ports:
      - '9000:9000'
      - '9000:9000/udp'
volumes:
  data: {}
